---
NEXUS:
      hostname: 172.16.4.1
      groups:
             - nexus
      
CORE-1:
      hostname: 192.168.28.136
      groups:
             - ios_routers
SW-STO01:
      hostname: 172.16.1.2
      groups: 
             - ios_switches
sto-cr01:
      hostname: 172.16.1.1
      groups:
             - ios_routers
fra-cr01:
      hostname: 172.16.3.1
      groups:
             - ios_routers
lon-cr01:
      hostname: 172.16.2.1
      groups:
             - ios_routers
fra-sw01:
      hostname: 172.16.3.2
      groups:
             - ios_switches
      data:
           function: l2
lon-sw01:
      hostname: 172.16.2.2
      groups:
             - ios_switches
      data:
           function: l2
